<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="uiCogentoFree CRM" duration-ms="71108" started-at="2023-06-29T09:27:33 IST" finished-at="2023-06-29T09:28:44 IST">
    <groups>
      <group name="Regression">
        <method signature="LoginPageTest.validateLoginFunctionality()[pri:1, instance:com.TestLayer.LoginPageTest@43738a82]" name="validateLoginFunctionality" class="com.TestLayer.LoginPageTest"/>
        <method signature="LoginPageTest.validateTitle()[pri:2, instance:com.TestLayer.LoginPageTest@43738a82]" name="validateTitle" class="com.TestLayer.LoginPageTest"/>
        <method signature="LoginPageTest.validateUrl()[pri:3, instance:com.TestLayer.LoginPageTest@43738a82]" name="validateUrl" class="com.TestLayer.LoginPageTest"/>
      </group> <!-- Regression -->
      <group name="LoginPage">
        <method signature="LoginPageTest.validateLoginFunctionality()[pri:1, instance:com.TestLayer.LoginPageTest@43738a82]" name="validateLoginFunctionality" class="com.TestLayer.LoginPageTest"/>
        <method signature="LoginPageTest.validateTitle()[pri:2, instance:com.TestLayer.LoginPageTest@43738a82]" name="validateTitle" class="com.TestLayer.LoginPageTest"/>
        <method signature="LoginPageTest.validateUrl()[pri:3, instance:com.TestLayer.LoginPageTest@43738a82]" name="validateUrl" class="com.TestLayer.LoginPageTest"/>
      </group> <!-- LoginPage -->
    </groups>
    <test name="Test" duration-ms="71108" started-at="2023-06-29T09:27:33 IST" finished-at="2023-06-29T09:28:44 IST">
      <class name="com.TestLayer.LoginPageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.TestLayer.LoginPageTest@43738a82]" name="setup" is-config="true" duration-ms="41739" started-at="2023-06-29T09:27:33 IST" finished-at="2023-06-29T09:28:15 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="validateLoginFunctionality()[pri:1, instance:com.TestLayer.LoginPageTest@43738a82]" name="validateLoginFunctionality" duration-ms="15181" started-at="2023-06-29T09:28:16 IST" finished-at="2023-06-29T09:28:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginFunctionality -->
        <test-method status="PASS" signature="validateTitle()[pri:2, instance:com.TestLayer.LoginPageTest@43738a82]" name="validateTitle" duration-ms="3414" started-at="2023-06-29T09:28:34 IST" finished-at="2023-06-29T09:28:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method status="FAIL" signature="validateUrl()[pri:3, instance:com.TestLayer.LoginPageTest@43738a82]" name="validateUrl" duration-ms="14" started-at="2023-06-29T09:28:38 IST" finished-at="2023-06-29T09:28:38 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.TestLayer.LoginPageTest.validateUrl(LoginPageTest.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUrl -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.TestLayer.LoginPageTest@43738a82]" name="teardown" is-config="true" duration-ms="4193" started-at="2023-06-29T09:28:39 IST" finished-at="2023-06-29T09:28:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.TestLayer.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- uiCogentoFree CRM -->
</testng-results>
